
server:
  port: 31212
spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://db:5432/students
    username: nikslav
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
resource-server:
  domain: http://resource-server:21212
frontend:
  domain: http://front-end:3000
dev-resource-server:
  domain: http://resource-server:21212
dev-frontend:
  domain: http://front-end:3000